version: '3.8'
services:
  movie-service:
    depends_on:
      - redis
      - kafka
    build: .
    container_name: movie-service
    environment:
      SPRING_R2DBC_URL: 
      SPRING_R2DBC_USERNAME: 
      SPRING_R2DBC_PASSWORD: 
      SPRING_SQL_INIT_MODE: 
      SPRING_REDIS_HOST: 
      SPRING_REDIS_PORT: 
      OMDBAPI_BASE_URL: 
      OMDBAPI_API_KEY: 
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 
      KAFKA_TOPIC_PREFIX: 
      KAFKA_TOPIC_RETENTION_DAYS: 
      AUTH_SERVICE_BASE_URL:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: 
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: 
      TWILIO_SENDGRID_EMAIL_API_KEY: 
      TWILIO_SENDGRID_EMAIL_API_URL:
      TWILIO_SENDGRID_EMAIL_API_SENDER_EMAIL:
      TWILIO_SENDGRID_EMAIL_API_SENDER_NAME: 
      OPENAI_API_KEY: 
      OPENAI_BASE_URL: 
      TMDB_BASE_URL:
      TMDB_API_KEY: 
    ports:
      - "9080:9080"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  kafka:
    depends_on:
      - postgres
      - zookeeper
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  redis:
    container_name: 'guide-redis'
    image: 'redis:latest'
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    container_name: movie_share_db
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5433:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
